#!/bin/bash
set -euo pipefail

CONFIG="${1?}"
VERSION="${2?}"
OPENCV_DIR="${3?}"
 
#git apply macos-4.8.1.patch || true

cmake "$OPENCV_DIR" -B "build_$CONFIG" \
  -DCMAKE_INSTALL_PREFIX=/usr/local \
  -DCMAKE_BUILD_TYPE="$CONFIG" \
  -DOPENCV_FORCE_3RDPARTY_BUILD=ON \
  -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 \
  -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" \
  -DBUILD_SHARED_LIBS=OFF \
  -DBUILD_opencv_apps=OFF \
  -DBUILD_opencv_js=OFF \
  -DBUILD_ANDROID_PROJECTS=OFF \
  -DBUILD_ANDROID_EXAMPLES=OFF \
  -DBUILD_DOCS=OFF \
  -DBUILD_EXAMPLES=OFF \
  -DBUILD_PACKAGE=OFF \
  -DBUILD_PERF_TESTS=OFF \
  -DBUILD_TESTS=OFF \
  -DBUILD_FAT_JAVA_LIB=OFF \
  -DBUILD_ANDROID_SERVICE=OFF \
  -DBUILD_JAVA=OFF \
  -DBUILD_OBJC=OFF \
  -DBUILD_opencv_python3=OFF \
  -DINSTALL_CREATE_DISTRIB=OFF \
  -DINSTALL_BIN_EXAMPLES=OFF \
  -DINSTALL_C_EXAMPLES=OFF \
  -DINSTALL_PYTHON_EXAMPLES=OFF \
  -DINSTALL_ANDROID_EXAMPLES=OFF \
  -DINSTALL_TO_MANGLED_PATHS=OFF \
  -DINSTALL_TESTS=OFF

cmake --build "build_$CONFIG"
cmake --install "build_$CONFIG" --prefix "release/$CONFIG"
tar -C "release/$CONFIG" -cvf "release/opencv-macos-$VERSION-$CONFIG.tar.gz" .
